// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: mls/message_contents/content.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Message content encoding structures
/// Copied from V2 code so that we can eventually retire all V2 message content

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Recognized compression algorithms
/// protolint:disable ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
public enum Xmtp_Mls_MessageContents_Compression: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case deflate // = 0
  case gzip // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .deflate
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .deflate
    case 1: self = .gzip
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .deflate: return 0
    case .gzip: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension Xmtp_Mls_MessageContents_Compression: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Xmtp_Mls_MessageContents_Compression] = [
    .deflate,
    .gzip,
  ]
}

#endif  // swift(>=4.2)

/// ContentTypeId is used to identify the type of content stored in a Message.
public struct Xmtp_Mls_MessageContents_ContentTypeId {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// authority governing this content type
  public var authorityID: String = String()

  /// type identifier
  public var typeID: String = String()

  /// major version of the type
  public var versionMajor: UInt32 = 0

  /// minor version of the type
  public var versionMinor: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// EncodedContent bundles the content with metadata identifying its type
/// and parameters required for correct decoding and presentation of the content.
public struct Xmtp_Mls_MessageContents_EncodedContent {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// content type identifier used to match the payload with
  /// the correct decoding machinery
  public var type: Xmtp_Mls_MessageContents_ContentTypeId {
    get {return _type ?? Xmtp_Mls_MessageContents_ContentTypeId()}
    set {_type = newValue}
  }
  /// Returns true if `type` has been explicitly set.
  public var hasType: Bool {return self._type != nil}
  /// Clears the value of `type`. Subsequent reads from it will return its default value.
  public mutating func clearType() {self._type = nil}

  /// optional encoding parameters required to correctly decode the content
  public var parameters: Dictionary<String,String> = [:]

  /// optional fallback description of the content that can be used in case
  /// the client cannot decode or render the content
  public var fallback: String {
    get {return _fallback ?? String()}
    set {_fallback = newValue}
  }
  /// Returns true if `fallback` has been explicitly set.
  public var hasFallback: Bool {return self._fallback != nil}
  /// Clears the value of `fallback`. Subsequent reads from it will return its default value.
  public mutating func clearFallback() {self._fallback = nil}

  /// optional compression; the value indicates algorithm used to
  /// compress the encoded content bytes
  public var compression: Xmtp_Mls_MessageContents_Compression {
    get {return _compression ?? .deflate}
    set {_compression = newValue}
  }
  /// Returns true if `compression` has been explicitly set.
  public var hasCompression: Bool {return self._compression != nil}
  /// Clears the value of `compression`. Subsequent reads from it will return its default value.
  public mutating func clearCompression() {self._compression = nil}

  /// encoded content itself
  public var content: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _type: Xmtp_Mls_MessageContents_ContentTypeId? = nil
  fileprivate var _fallback: String? = nil
  fileprivate var _compression: Xmtp_Mls_MessageContents_Compression? = nil
}

/// A PlaintextEnvelope is the outermost payload that gets encrypted by MLS
public struct Xmtp_Mls_MessageContents_PlaintextEnvelope {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Selector which declares which version of the EncodedContent this
  /// PlaintextEnvelope is
  public var content: Xmtp_Mls_MessageContents_PlaintextEnvelope.OneOf_Content? = nil

  public var v1: Xmtp_Mls_MessageContents_PlaintextEnvelope.V1 {
    get {
      if case .v1(let v)? = content {return v}
      return Xmtp_Mls_MessageContents_PlaintextEnvelope.V1()
    }
    set {content = .v1(newValue)}
  }

  public var v2: Xmtp_Mls_MessageContents_PlaintextEnvelope.V2 {
    get {
      if case .v2(let v)? = content {return v}
      return Xmtp_Mls_MessageContents_PlaintextEnvelope.V2()
    }
    set {content = .v2(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Selector which declares which version of the EncodedContent this
  /// PlaintextEnvelope is
  public enum OneOf_Content: Equatable {
    case v1(Xmtp_Mls_MessageContents_PlaintextEnvelope.V1)
    case v2(Xmtp_Mls_MessageContents_PlaintextEnvelope.V2)

  #if !swift(>=4.1)
    public static func ==(lhs: Xmtp_Mls_MessageContents_PlaintextEnvelope.OneOf_Content, rhs: Xmtp_Mls_MessageContents_PlaintextEnvelope.OneOf_Content) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.v1, .v1): return {
        guard case .v1(let l) = lhs, case .v1(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.v2, .v2): return {
        guard case .v2(let l) = lhs, case .v2(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  /// Version 1 of the encrypted envelope
  public struct V1 {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Expected to be EncodedContent
    public var content: Data = Data()

    /// A unique value that can be used to ensure that the same content can
    /// produce different hashes. May be the sender timestamp.
    public var idempotencyKey: String = String()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  /// Version 2 of the encrypted envelope
  public struct V2 {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var messageType: Xmtp_Mls_MessageContents_PlaintextEnvelope.V2.OneOf_MessageType? = nil

    /// Expected to be EncodedContent
    public var content: Data {
      get {
        if case .content(let v)? = messageType {return v}
        return Data()
      }
      set {messageType = .content(newValue)}
    }

    /// Initiator sends the request to receive history
    public var messageHistoryRequest: Xmtp_Mls_MessageContents_MessageHistoryRequest {
      get {
        if case .messageHistoryRequest(let v)? = messageType {return v}
        return Xmtp_Mls_MessageContents_MessageHistoryRequest()
      }
      set {messageType = .messageHistoryRequest(newValue)}
    }

    /// Other credentialed party sends response
    public var messageHistoryResponse: Xmtp_Mls_MessageContents_MessageHistoryResponse {
      get {
        if case .messageHistoryResponse(let v)? = messageType {return v}
        return Xmtp_Mls_MessageContents_MessageHistoryResponse()
      }
      set {messageType = .messageHistoryResponse(newValue)}
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public enum OneOf_MessageType: Equatable {
      /// Expected to be EncodedContent
      case content(Data)
      /// Initiator sends the request to receive history
      case messageHistoryRequest(Xmtp_Mls_MessageContents_MessageHistoryRequest)
      /// Other credentialed party sends response
      case messageHistoryResponse(Xmtp_Mls_MessageContents_MessageHistoryResponse)

    #if !swift(>=4.1)
      public static func ==(lhs: Xmtp_Mls_MessageContents_PlaintextEnvelope.V2.OneOf_MessageType, rhs: Xmtp_Mls_MessageContents_PlaintextEnvelope.V2.OneOf_MessageType) -> Bool {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch (lhs, rhs) {
        case (.content, .content): return {
          guard case .content(let l) = lhs, case .content(let r) = rhs else { preconditionFailure() }
          return l == r
        }()
        case (.messageHistoryRequest, .messageHistoryRequest): return {
          guard case .messageHistoryRequest(let l) = lhs, case .messageHistoryRequest(let r) = rhs else { preconditionFailure() }
          return l == r
        }()
        case (.messageHistoryResponse, .messageHistoryResponse): return {
          guard case .messageHistoryResponse(let l) = lhs, case .messageHistoryResponse(let r) = rhs else { preconditionFailure() }
          return l == r
        }()
        default: return false
        }
      }
    #endif
    }

    public init() {}
  }

  public init() {}
}

/// The initiator or new installation id that is requesting a history will send a
/// request
public struct Xmtp_Mls_MessageContents_MessageHistoryRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var requestID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Pre-existing installation id that is capable of supplying a history will send
/// this response
public struct Xmtp_Mls_MessageContents_MessageHistoryResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var requestID: String = String()

  public var backupURL: String = String()

  public var backupFileHash: Data = Data()

  public var expirationTimeNs: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Xmtp_Mls_MessageContents_Compression: @unchecked Sendable {}
extension Xmtp_Mls_MessageContents_ContentTypeId: @unchecked Sendable {}
extension Xmtp_Mls_MessageContents_EncodedContent: @unchecked Sendable {}
extension Xmtp_Mls_MessageContents_PlaintextEnvelope: @unchecked Sendable {}
extension Xmtp_Mls_MessageContents_PlaintextEnvelope.OneOf_Content: @unchecked Sendable {}
extension Xmtp_Mls_MessageContents_PlaintextEnvelope.V1: @unchecked Sendable {}
extension Xmtp_Mls_MessageContents_PlaintextEnvelope.V2: @unchecked Sendable {}
extension Xmtp_Mls_MessageContents_PlaintextEnvelope.V2.OneOf_MessageType: @unchecked Sendable {}
extension Xmtp_Mls_MessageContents_MessageHistoryRequest: @unchecked Sendable {}
extension Xmtp_Mls_MessageContents_MessageHistoryResponse: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "xmtp.mls.message_contents"

extension Xmtp_Mls_MessageContents_Compression: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "COMPRESSION_DEFLATE"),
    1: .same(proto: "COMPRESSION_GZIP"),
  ]
}

extension Xmtp_Mls_MessageContents_ContentTypeId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ContentTypeId"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "authority_id"),
    2: .standard(proto: "type_id"),
    3: .standard(proto: "version_major"),
    4: .standard(proto: "version_minor"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.authorityID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.typeID) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.versionMajor) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.versionMinor) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.authorityID.isEmpty {
      try visitor.visitSingularStringField(value: self.authorityID, fieldNumber: 1)
    }
    if !self.typeID.isEmpty {
      try visitor.visitSingularStringField(value: self.typeID, fieldNumber: 2)
    }
    if self.versionMajor != 0 {
      try visitor.visitSingularUInt32Field(value: self.versionMajor, fieldNumber: 3)
    }
    if self.versionMinor != 0 {
      try visitor.visitSingularUInt32Field(value: self.versionMinor, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xmtp_Mls_MessageContents_ContentTypeId, rhs: Xmtp_Mls_MessageContents_ContentTypeId) -> Bool {
    if lhs.authorityID != rhs.authorityID {return false}
    if lhs.typeID != rhs.typeID {return false}
    if lhs.versionMajor != rhs.versionMajor {return false}
    if lhs.versionMinor != rhs.versionMinor {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xmtp_Mls_MessageContents_EncodedContent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".EncodedContent"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "type"),
    2: .same(proto: "parameters"),
    3: .same(proto: "fallback"),
    5: .same(proto: "compression"),
    4: .same(proto: "content"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._type) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.parameters) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._fallback) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.content) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self._compression) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._type {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.parameters.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.parameters, fieldNumber: 2)
    }
    try { if let v = self._fallback {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    if !self.content.isEmpty {
      try visitor.visitSingularBytesField(value: self.content, fieldNumber: 4)
    }
    try { if let v = self._compression {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xmtp_Mls_MessageContents_EncodedContent, rhs: Xmtp_Mls_MessageContents_EncodedContent) -> Bool {
    if lhs._type != rhs._type {return false}
    if lhs.parameters != rhs.parameters {return false}
    if lhs._fallback != rhs._fallback {return false}
    if lhs._compression != rhs._compression {return false}
    if lhs.content != rhs.content {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xmtp_Mls_MessageContents_PlaintextEnvelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PlaintextEnvelope"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "v1"),
    2: .same(proto: "v2"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Xmtp_Mls_MessageContents_PlaintextEnvelope.V1?
        var hadOneofValue = false
        if let current = self.content {
          hadOneofValue = true
          if case .v1(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.content = .v1(v)
        }
      }()
      case 2: try {
        var v: Xmtp_Mls_MessageContents_PlaintextEnvelope.V2?
        var hadOneofValue = false
        if let current = self.content {
          hadOneofValue = true
          if case .v2(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.content = .v2(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.content {
    case .v1?: try {
      guard case .v1(let v)? = self.content else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .v2?: try {
      guard case .v2(let v)? = self.content else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xmtp_Mls_MessageContents_PlaintextEnvelope, rhs: Xmtp_Mls_MessageContents_PlaintextEnvelope) -> Bool {
    if lhs.content != rhs.content {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xmtp_Mls_MessageContents_PlaintextEnvelope.V1: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Xmtp_Mls_MessageContents_PlaintextEnvelope.protoMessageName + ".V1"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "content"),
    2: .standard(proto: "idempotency_key"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.content) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.idempotencyKey) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.content.isEmpty {
      try visitor.visitSingularBytesField(value: self.content, fieldNumber: 1)
    }
    if !self.idempotencyKey.isEmpty {
      try visitor.visitSingularStringField(value: self.idempotencyKey, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xmtp_Mls_MessageContents_PlaintextEnvelope.V1, rhs: Xmtp_Mls_MessageContents_PlaintextEnvelope.V1) -> Bool {
    if lhs.content != rhs.content {return false}
    if lhs.idempotencyKey != rhs.idempotencyKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xmtp_Mls_MessageContents_PlaintextEnvelope.V2: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Xmtp_Mls_MessageContents_PlaintextEnvelope.protoMessageName + ".V2"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "content"),
    2: .standard(proto: "message_history_request"),
    3: .standard(proto: "message_history_response"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.messageType != nil {try decoder.handleConflictingOneOf()}
          self.messageType = .content(v)
        }
      }()
      case 2: try {
        var v: Xmtp_Mls_MessageContents_MessageHistoryRequest?
        var hadOneofValue = false
        if let current = self.messageType {
          hadOneofValue = true
          if case .messageHistoryRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.messageType = .messageHistoryRequest(v)
        }
      }()
      case 3: try {
        var v: Xmtp_Mls_MessageContents_MessageHistoryResponse?
        var hadOneofValue = false
        if let current = self.messageType {
          hadOneofValue = true
          if case .messageHistoryResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.messageType = .messageHistoryResponse(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.messageType {
    case .content?: try {
      guard case .content(let v)? = self.messageType else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
    }()
    case .messageHistoryRequest?: try {
      guard case .messageHistoryRequest(let v)? = self.messageType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .messageHistoryResponse?: try {
      guard case .messageHistoryResponse(let v)? = self.messageType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xmtp_Mls_MessageContents_PlaintextEnvelope.V2, rhs: Xmtp_Mls_MessageContents_PlaintextEnvelope.V2) -> Bool {
    if lhs.messageType != rhs.messageType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xmtp_Mls_MessageContents_MessageHistoryRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MessageHistoryRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "request_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xmtp_Mls_MessageContents_MessageHistoryRequest, rhs: Xmtp_Mls_MessageContents_MessageHistoryRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xmtp_Mls_MessageContents_MessageHistoryResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MessageHistoryResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "request_id"),
    2: .standard(proto: "backup_url"),
    3: .standard(proto: "backup_file_hash"),
    4: .standard(proto: "expiration_time_ns"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.backupURL) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.backupFileHash) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.expirationTimeNs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 1)
    }
    if !self.backupURL.isEmpty {
      try visitor.visitSingularStringField(value: self.backupURL, fieldNumber: 2)
    }
    if !self.backupFileHash.isEmpty {
      try visitor.visitSingularBytesField(value: self.backupFileHash, fieldNumber: 3)
    }
    if self.expirationTimeNs != 0 {
      try visitor.visitSingularInt64Field(value: self.expirationTimeNs, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xmtp_Mls_MessageContents_MessageHistoryResponse, rhs: Xmtp_Mls_MessageContents_MessageHistoryResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.backupURL != rhs.backupURL {return false}
    if lhs.backupFileHash != rhs.backupFileHash {return false}
    if lhs.expirationTimeNs != rhs.expirationTimeNs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
