included:
  - Sources
  - XMTPiOSExample
excluded:
  - Tests
  - Sources/XMTPiOS/Libxmtp/xmtpv3.swift
  - Sources/XMTPiOS/Proto

disabled_rules: # rule identifiers turned on by default to exclude from running
  - type_name
  - identifier_name
  - multiple_closures_with_trailing_closure
  - cyclomatic_complexity
  - trailing_comma
  - opening_brace
  - nesting
  - type_body_length
  - file_length
  - todo
  - control_statement
  - switch_case_alignment
  - empty_enum_arguments
  - for_where
  - private_over_fileprivate
  - redundant_string_enum_value
  - implicit_optional_initialization
  - function_name_whitespace
  - comma
  - no_optional_try

opt_in_rules:
  - force_unwrapping

force_unwrapping:
  severity: error

line_length: 500

custom_rules:
  no_optional_try:
    included:
      - ".*\\.swift"
    name: "No optional try"
    regex: try[\\?]
    capture_group: 0
    message: "Handle this error instead of doing this.."
    severity: error
