excluded:
  - Sources/XMTP/Proto

disabled_rules: # rule identifiers turned on by default to exclude from running
  - type_name
  - identifier_name
  - multiple_closures_with_trailing_closure
  - cyclomatic_complexity
  - trailing_comma
  - opening_brace
  - nesting
  - type_body_length
  - file_length
  - todo
  - control_statement
  - switch_case_alignment
  - empty_enum_arguments
  - for_where
  - private_over_fileprivate
  - redundant_string_enum_value
  - redundant_optional_initialization
  - operator_whitespace
  - comma
  - no_optional_try

opt_in_rules:
  - force_unwrapping

force_unwrapping:
  severity: error

line_length: 500

custom_rules:
  no_optional_try: # rule identifier
    included:
      - ".*\\.swift" # regex that defines paths to include during linting. optional.
    excluded:
      - ".*Tests?\\.swift" # regex that defines paths to exclude during linting. optional
    name: "No optional try" # rule name. optional.
    regex: try[\\?]
    capture_group: 0 # number of regex capture group to highlight the rule violation at. optional.
    message: "Handle this error instead of doing this.." # violation message. optional.
    severity: error # violation severity. optional.
    #match_kinds:# SyntaxKinds to match. optional.
    #   - comment
    # - identifier
