# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'NotificationService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NotificationService
	# Pods for XMTPiOSExample
	# pod "secp256k1Swift", git: "https://github.com/portto/secp256k1.swift"
  pod "web3.swift"
#  pod "XMTPProto", path: "../../proto"
#	pod "XMTPRust", path: '../../xmtp-rust-swift'
	pod "XMTP", "= 0.1.3-beta0"
end

target 'XMTPiOSExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XMTPiOSExample
  # pod "secp256k1Swift", git: "https://github.com/portto/secp256k1.swift"
  pod "web3.swift"
#  pod "XMTPProto", path: "../../proto"
#  pod "XMTPRust", path: '../../xmtp-rust-swift'
	pod "XMTP", "= 0.1.3-beta0"
end

post_install do |installer|
	installer.generated_projects.each do |project|
		project.targets.each do |target|
			target.build_configurations.each do |config|
				config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
			 end
		end
	end
end
