name: Build dosc

on:
  push:
    branches: [ "main", "docs" ]
  pull_request:

jobs:
  build:
    name: Run swiftlint
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v3
      - run: swift package --allow-writing-to-directory ./docs generate-documentation --target XMTP --disable-indexing --output-path ./docs
