name: Deploy docs content to GitHub Pages

on:
  push:
    branches: ["main", "docs"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Swift package
        run: swift build

      - name: Generate documentation
        run: |
          swift package --allow-writing-to-directory ./docs \
            generate-documentation \
            --target XMTPiOS \
            --output-path ./docs \
            --transform-for-static-hosting \
            --hosting-base-path xmtp-ios

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
