name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: Run swiftlint
    runs-on: warp-macos-14-arm64-6x
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: actions/checkout@v3

      # Install swiftlint
      - name: Install swiftlint
        run: brew install swiftlint

      # Run swiftlint
      - name: Run swiftlint
        run: swiftlint Sources/ XMTPiOSExample/XMTPiOSExample

      # Lint the podspec
      - name: Lint podspec
        run: pod lib lint --allow-warnings
