name: Lint

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
      - name: Run SwiftLint
        run: ./dev/lint

  swiftformat:
    name: SwiftFormat
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
      - name: Install SwiftFormat
        run: brew install swiftformat
      - name: Check SwiftFormat
        run: ./dev/fmt --lint
