name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: Run swiftlint
    runs-on: warp-macos-14-arm64-6x
    steps:
      - uses: actions/checkout@v3
      - run: pod lib lint --allow-warnings
