name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: Run swiftlint
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - run: swiftlint Sources/ XMTPiOSExample/XMTPiOSExample
      - run: pod lib lint --allow-warnings
