name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: Run swiftlint
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v3
      - run: script/lint
