name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: swiftlint
        run: swiftlint --strict
      - run: pod lib lint --allow-warnings
