name: Tag and deploy to Cocoapods

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Install Cocoapods
      run: gem install cocoapods
    
    - name: Extract version from podspec
      id: extract_version
      run: |
        SPEC_VERSION=$(grep 'spec.version' XMTP.podspec | sed -n 's/.*spec\.version *= *"\([^"]*\)".*/\1/p')
        echo "SPEC_VERSION=$SPEC_VERSION" >> $GITHUB_ENV
        echo "Original version: $SPEC_VERSION"
    
    - name: Update version if dev release
      id: update_version
      run: |
        SHORT_SHA=$(git rev-parse --short=7 HEAD)
        if [[ "$SPEC_VERSION" == *"dev"* ]]; then
          UPDATED_VERSION="${SPEC_VERSION}.$SHORT_SHA"
        else
          UPDATED_VERSION="$SPEC_VERSION"
        fi
        echo "UPDATED_VERSION=$UPDATED_VERSION" >> $GITHUB_ENV
        echo "Updated version: $UPDATED_VERSION"
    
    - name: Update podspec with new version
      run: |
        sed -i '' "s/spec\.version *= *\"$SPEC_VERSION\"/spec.version = \"$UPDATED_VERSION\"/" XMTP.podspec
        echo "Updated podspec with version: $UPDATED_VERSION"
    
    - name: Create and push tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a "$UPDATED_VERSION" -m "Release $UPDATED_VERSION"
        git push origin "$UPDATED_VERSION"
        echo "Created and pushed tag: $UPDATED_VERSION"

    - name: Extract LibXMTPSwiftFFI URL from Package.swift
      id: extract_url
      run: |
        ZIP_URL=$(grep -A 2 'name: "LibXMTPSwiftFFI"' Package.swift | grep 'url:' | sed -n 's/.*url: *"\([^"]*\)".*/\1/p')
        echo "ZIP_URL=$ZIP_URL" >> $GITHUB_ENV
        echo "Extracted URL: $ZIP_URL"

    - name: Build release archive (Sources + LibXMTPSwiftFFI.xcframework)
      run: |
        set -euo pipefail
        curl -L "$ZIP_URL" -o LibXMTPSwiftFFI.zip
        rm -rf LibXMTPSwiftFFI.xcframework
        unzip -qo LibXMTPSwiftFFI.zip 'LibXMTPSwiftFFI.xcframework/*' -d .
        rm -f LibXMTPSwiftFFI.zip
        rm -rf bundle && mkdir -p bundle
        rsync -a --exclude 'LibXMTPSwiftFFI.xcframework' Sources/ bundle/Sources/
        mv LibXMTPSwiftFFI.xcframework bundle/
        (cd bundle && zip -qry ../XMTP-${UPDATED_VERSION}.zip .)

    - name: Create GitHub Release and upload asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.UPDATED_VERSION }}
        name: ${{ env.UPDATED_VERSION }}
        files: XMTP-${{ env.UPDATED_VERSION }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        pod spec lint XMTP.podspec --quick --platforms=ios --allow-warnings
        pod trunk push XMTP.podspec --allow-warnings --skip-import-validation
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
