name: iOS Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GPR_USER: ${{ secrets.GITHUB_ACTOR }}

jobs:
  ios-tests:
    name: iOS Tests
    runs-on: macos-13

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Set up Docker
        run: brew install docker colima docker-compose
      
      - name: Start Colima
        run: colima start
        
      - name: Start Docker containers
        run: ./dev/up
        
        # retries are added due to test failures with dependencies
      - name: Run tests
        run: xcodebuild test -scheme XMTP -destination "platform=iOS Simulator,name=iPhone 14" 
        
      - name: Stop local test server
        run: docker-compose -p xmtp-ios -f dev/local/docker-compose.yml down
