name: iOS Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GPR_USER: ${{ secrets.GITHUB_ACTOR }}

jobs:
  ios-tests:
    name: iOS Tests
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Install Docker CLI
        run: brew install docker docker-compose

      - name: Check Docker status
        run: docker info

      - name: Start local containers
        run: dev/up

      - name: Run tests
        run: script/run_tests.sh

      - name: Stop local test server
        run: docker-compose -p xmtp-ios -f dev/local/docker-compose.yml down
