jobs:
  ios-tests:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Install working Python for Colima
        run: |
          brew uninstall --ignore-dependencies python@3.12 || true
          brew install python@3.11
          brew link --overwrite python@3.11

      - name: Install Colima + Docker
        run: |
          brew install colima docker docker-compose
          colima start --cpu 2 --memory 4 --disk 20

      - name: Start containers
        run: dev/up

      - name: Run iOS tests
        run: script/run_tests.sh

      - name: Teardown
        run: docker-compose -p xmtp-ios -f dev/local/docker-compose.yml down
